server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: userservice
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  threads:
    virtual:
      enabled: true
eureka:
  client:
    service-url:
      "defaultZone": ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: false
  instance:
    prefer-ip-address: true
#    PLEASE CHANGE THIS TO AN ENV-VAR...
jwt:
  private_key:
    "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCuFU4Uhk81D1Aa49/wARRGK0RarNpDTPRhUou88bYldwgfI2yN2kpDbihlqfm8A941Kfom82QyNe//gd0a4CA8JeK3lC9ihJPQ7PyqGkSnoszHr1QdpS28NsQV6jilQEA+ZmrkMG3bsCVNbCgGA64mSfvix6ve+KJjLYpTjFgA1evut5wKw3+onon2czyxaHpOgWli+oEakpd3yAFWAV2hB8HPLMwlRWvJabrkvYwHPE2tHGy/eWQCtzIl0wtUlp3fY9HQUSvQ7NXwYP4GCEMAz64DD1YIhX1wf09Ua8WMCSdlB9vnWzPOZBMyFKuAmtsjJgSr0JxjM4LthT7Ssq9xAgMBAAECggEAIy3zBXrO7u4VRhne22Wcb0G3Iovj383hZPmFe71tDc0sOv6xpUkD0PSl/UWITlKJyTyebNiq2urDgWMBB7lbSkxtsKOln8cjCAmcVdPRI/9mWsQ3v3Xt9CctITCgGeUOFo4j89FFoivKngbJX83Gl75DxOSM+xZL2rcNSS0Ha8N54ZHhIonxRm5+upA/fItSH7oJAsqZDyksgaxZTKcXg1eE+2Au5g1U9xuugXQL/D04poePcls96a6zosPeiP9gT2SnTHlRHYNp7f7/CWSjwSv1lnJ3eQAE1zCoE6At6uqIORW1LWlScEI5CcRlvPbmtSn6+Q2lX7Erb9x+HYDQQQKBgQDfN97uAzRrdE8AaH/z4s/r4GSswYlzSfbgWoQXalaRwtfSvqWkJCz/owEDf0iE0grj9tmf2lf6uivAUMLqI0gBe50fYTlOEmmVq5Up1l/gh0te5P+n+c7jF2aloy/dCl3caLteNvKWL/e51baSEE0HGQszUfmqQpIarxqD2VwtXQKBgQDHpiZ8nX8T40kswJ0JARuPESxDdRGRr3kVT1nQiniJU86Bwhrd97xHQsWy49Kh6mc1hvAvv2y2vPlJwNC0KE0d2As535Q9fIzZaJOZQyXtTYdFZ/nqm5i4+zQMMKYw0P0crfA08ynCUHlQPMtIMJTjz6OXOfj/A4J/L/W1wU2VJQKBgGNp+rt+aeZBkr3XzMTOC1Q+SBg4ygKyumUJazMShSO952lQx2znP7NK4bSxB5dABOGqmxn6oJxmNf4c+fJVbEhcyYmkP2VqBeRG2tQbSfAx0Xud+c7SDzZMwcabe0Gy0ELN0kUPq9L/4hC+AeXjpKq4mKhupgcSRwfjXKfEMq1xAoGBAMWDdqfqGIJQZWBE3ha+ZclQL/48nzkF5EBU1IIfu8gAhViR84qNQFMvl+62vPc6swidiplyQ9c1dVqlytOw2zofNlv2+O0rfxzG/N6vM6JlBOKBTxnu/VRkEMXOi1vYJdBttCpuNm3qt1nOCz5L8cC+9xTxYYjIrB2wEOHTbzGRAoGAOMolah/NirRzlnAliYYrBds+WAtcxmM4Hwdq8ojc20euBJNk/ZQMRlwNR133qs/PihObrNWw9/s/TjyAL2Wxs+RUjx69aYWrJPYfZwP6FsAie4DPp7uaSbC3RVnhURws7ycYVIzVLV4q32R66PCTiOlgxioj0iZXmNNAblagptU="
  public_key:
    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArhVOFIZPNQ9QGuPf8AEURitEWqzaQ0z0YVKLvPG2JXcIHyNsjdpKQ24oZan5vAPeNSn6JvNkMjXv/4HdGuAgPCXit5QvYoST0Oz8qhpEp6LMx69UHaUtvDbEFeo4pUBAPmZq5DBt27AlTWwoBgOuJkn74ser3viiYy2KU4xYANXr7recCsN/qJ6J9nM8sWh6ToFpYvqBGpKXd8gBVgFdoQfBzyzMJUVryWm65L2MBzxNrRxsv3lkArcyJdMLVJad32PR0FEr0OzV8GD+BghDAM+uAw9WCIV9cH9PVGvFjAknZQfb51szzmQTMhSrgJrbIyYEq9CcYzOC7YU+0rKvcQIDAQAB"
logging:
  level:
    org.apache.kafka: WARN
    kafka: WARN
    kafka.admin: WARN